using CodeGenerator.Core.Enums;
using CodeGenerator.Core.Models.Schema;

namespace CodeGenerator.Core.Models.Domain;

/// <summary>
/// Parsed property model
/// </summary>
public class PropertyModel
{
    /// <summary>
    /// Property name
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// CLR type name
    /// </summary>
    public string TypeName { get; set; } = string.Empty;

    /// <summary>
    /// Whether the property is nullable
    /// </summary>
    public bool IsNullable { get; set; }

    /// <summary>
    /// Whether this is a required property
    /// </summary>
    public bool IsRequired { get; set; }

    /// <summary>
    /// Description from schema
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Default value
    /// </summary>
    public object? DefaultValue { get; set; }

    /// <summary>
    /// Data type category
    /// </summary>
    public PropertyDataType DataType { get; set; }

    /// <summary>
    /// Maximum length for strings
    /// </summary>
    public int? MaxLength { get; set; }

    /// <summary>
    /// Minimum length for strings
    /// </summary>
    public int? MinLength { get; set; }

    /// <summary>
    /// Minimum value for numbers
    /// </summary>
    public decimal? Minimum { get; set; }

    /// <summary>
    /// Maximum value for numbers
    /// </summary>
    public decimal? Maximum { get; set; }

    /// <summary>
    /// Regex pattern for validation
    /// </summary>
    public string? Pattern { get; set; }

    /// <summary>
    /// Enum values if this is an enum type
    /// </summary>
    public List<EnumValue>? EnumValues { get; set; }

    /// <summary>
    /// Whether this is a primary key
    /// </summary>
    public bool IsPrimaryKey { get; set; }

    /// <summary>
    /// Whether this is a foreign key
    /// </summary>
    public bool IsForeignKey { get; set; }

    /// <summary>
    /// Whether this is auto-generated
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Whether this is computed
    /// </summary>
    public bool IsComputed { get; set; }

    /// <summary>
    /// Whether this is read-only
    /// </summary>
    public bool IsReadOnly { get; set; }

    /// <summary>
    /// Code generation settings
    /// </summary>
    public PropertyCodeGenMetadata? CodeGenSettings { get; set; }

    /// <summary>
    /// Database settings
    /// </summary>
    public PropertyDatabaseMetadata? DatabaseSettings { get; set; }

    /// <summary>
    /// Display settings for UI
    /// </summary>
    public DisplaySettings? DisplaySettings { get; set; }

    /// <summary>
    /// Validation rules
    /// </summary>
    public List<ValidationRule> ValidationRules { get; set; } = new();

    /// <summary>
    /// Attributes to apply
    /// </summary>
    public List<AttributeModel> Attributes { get; set; } = new();

    /// <summary>
    /// Original property definition
    /// </summary>
    public PropertyDefinition? OriginalDefinition { get; set; }
}
