using CodeGenerator.Core.Enums;
using CodeGenerator.Core.Generators;
using CodeGenerator.Core.Interfaces;
using CodeGenerator.Core.Models.Configuration;
using CodeGenerator.Core.Models.Domain;
using CodeGenerator.Core.Models.Output;
using Microsoft.Extensions.Logging;

namespace CodeGenerator.Generators.Infrastructure;

/// <summary>
/// Generates SQL database scripts
/// </summary>
public class DbScriptGenerator : BaseCodeGenerator
{
    public override string Id => "DbScript";
    public override string Name => "Database Script Generator";
    public override string Description => "Generates SQL database scripts";
    public override GeneratorType Type => GeneratorType.DbScript;
    public override ArchitectureLayer Layer => ArchitectureLayer.Infrastructure;

    public override IReadOnlyList<TargetLanguage> SupportedLanguages => new[]
    {
        TargetLanguage.SQL_SqlServer,
        TargetLanguage.SQL_PostgreSQL,
        TargetLanguage.SQL_MySQL,
        TargetLanguage.SQL_SQLite
    };

    public DbScriptGenerator(
        ITemplateEngine templateEngine,
        IFileService fileService,
        ILogger<DbScriptGenerator> logger)
        : base(templateEngine, fileService, logger)
    {
    }

    public override async Task<GenerationResult> GenerateForEntityAsync(
        EntityModel entity,
        DomainContext context,
        GeneratorSettings settings,
        CancellationToken cancellationToken = default)
    {
        var result = new GenerationResult();
        var config = GetConfiguration(settings);

        if (config == null || !config.Enabled)
        {
            result.Success = true;
            return result;
        }

        // Skip owned types - they're embedded in parent tables
        if (entity.IsOwnedType)
        {
            result.Success = true;
            return result;
        }

        try
        {
            foreach (var template in config.Templates.Where(t => t.PerEntity))
            {
                var file = await RenderAndCreateFile(template, entity, context, settings, cancellationToken);
                result.Files.Add(file);

                if (settings.OverwriteExisting || file.IsNew)
                {
                    await FileService.WriteFileAsync(file.AbsolutePath, file.Content, settings.CreateBackup, cancellationToken);
                    file.Written = true;
                    Logger.LogInformation("Generated SQL script for {EntityName} at {Path}", entity.Name, file.AbsolutePath);
                }
            }

            result.Success = true;
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Failed to generate SQL script for {EntityName}", entity.Name);
            result.Errors.Add($"Failed to generate SQL script for {entity.Name}: {ex.Message}");
            result.Success = false;
        }

        return result;
    }

    protected override object CreateTemplateModel(EntityModel entity, DomainContext context, GeneratorSettings settings)
    {
        var tableName = entity.DatabaseSettings?.TableName ?? entity.Name;
        var schema = entity.DatabaseSettings?.Schema ?? context.DatabaseMetadata?.Schema ?? "dbo";

        return new
        {
            Entity = entity,
            Context = context,
            Settings = settings,
            TableName = tableName,
            Schema = schema,
            FullTableName = $"[{schema}].[{tableName}]",
            Columns = entity.Properties.Select(p => MapToColumn(p, settings)).ToList(),
            PrimaryKey = GetPrimaryKeyConstraint(entity),
            ForeignKeys = GetForeignKeyConstraints(entity, context),
            Indexes = entity.DatabaseSettings?.Indexes ?? new List<Core.Models.Schema.IndexDefinition>(),
            Generator = new { Id, Name, GeneratedAt = DateTime.UtcNow }
        };
    }

    private object MapToColumn(PropertyModel property, GeneratorSettings settings)
    {
        var dbSettings = property.DatabaseSettings;
        var columnName = dbSettings?.ColumnName ?? property.Name;
        var sqlType = dbSettings?.ColumnType ?? GetSqlType(property);
        var isNullable = property.IsNullable && !property.IsPrimaryKey;
        var defaultValue = dbSettings?.DefaultConstraint;

        return new
        {
            Name = columnName,
            SqlType = sqlType,
            IsNullable = isNullable,
            IsPrimaryKey = property.IsPrimaryKey,
            IsIdentity = property.IsAutoGenerated,
            IsUnique = dbSettings?.IsUnique ?? false,
            DefaultValue = defaultValue,
            property.Description
        };
    }

    private string GetSqlType(PropertyModel property)
    {
        var maxLength = property.MaxLength;
        
        return property.DataType switch
        {
            PropertyDataType.String when maxLength.HasValue => $"NVARCHAR({maxLength})",
            PropertyDataType.String => "NVARCHAR(MAX)",
            PropertyDataType.Integer => "INT",
            PropertyDataType.Long => "BIGINT",
            PropertyDataType.Decimal => "DECIMAL(18,2)",
            PropertyDataType.Double => "FLOAT",
            PropertyDataType.Float => "REAL",
            PropertyDataType.Boolean => "BIT",
            PropertyDataType.DateTime => "DATETIME2",
            PropertyDataType.DateOnly => "DATE",
            PropertyDataType.TimeOnly => "TIME",
            PropertyDataType.Guid => "UNIQUEIDENTIFIER",
            PropertyDataType.Binary => "VARBINARY(MAX)",
            _ => "NVARCHAR(MAX)"
        };
    }

    private object? GetPrimaryKeyConstraint(EntityModel entity)
    {
        var pkProperties = entity.PrimaryKeyProperties;
        if (!pkProperties.Any()) return null;

        return new
        {
            Name = $"PK_{entity.Name}",
            Columns = pkProperties.Select(p => p.DatabaseSettings?.ColumnName ?? p.Name).ToList()
        };
    }

    private List<object> GetForeignKeyConstraints(EntityModel entity, DomainContext context)
    {
        var fks = new List<object>();

        foreach (var nav in entity.NavigationProperties.Where(n => n.RelationshipType == RelationshipType.ManyToOne))
        {
            var targetEntity = context.Entities.FirstOrDefault(e => e.Name == nav.TargetEntity);
            if (targetEntity == null) continue;

            var fkProperty = nav.ForeignKeyProperty ?? $"{nav.Name}Id";
            var targetPk = targetEntity.PrimaryKeyProperties.FirstOrDefault();

            fks.Add(new
            {
                Name = $"FK_{entity.Name}_{nav.TargetEntity}",
                Column = fkProperty,
                ReferencedTable = targetEntity.DatabaseSettings?.TableName ?? targetEntity.Name,
                ReferencedColumn = targetPk?.DatabaseSettings?.ColumnName ?? targetPk?.Name ?? "Id",
                OnDelete = nav.IsNullable ? "SET NULL" : "CASCADE"
            });
        }

        return fks;
    }
}
